backend = CPU
seed = 42001

sim_type = VMMC
ensemble = NVT
steps = 50000000
equilibration_steps = 200000

delta_translation = 0.15
delta_rotation = 0.15
verlet_skin = 0.30
T = 65C
T_force_value = true

small_system = 1

umbrella_sampling = 1
op_file = op.txt
weights_file = wfile_converged.txt

extrapolate_hist = 37C, 51C, 65C, 79C, 93C, 107C
last_hist_file = hist_prod.dat
traj_hist_file = traj_hist_prod.dat

topology = hairpin.top
conf_file = last_conf.dat
trajectory_file = traj_prod.dat
energy_file = energy_prod.dat
last_conf_file = last_conf_prod.dat

print_conf_interval = 50000
print_energy_every = 1000000
no_stdout_energy = 1
restart_step_counter = 1
refresh_vel = 1
time_scale = linear
