backend = CPU
seed = 20003
sim_type = VMMC
ensemble = NVT
steps = 3000000
equilibration_steps = 50000
delta_translation = 0.15
delta_rotation = 0.15
verlet_skin = 0.30
T = 0.11733
small_system = 1
umbrella_sampling = 1
op_file = op.txt
weights_file = wfile.txt
last_hist_file = hist_wl3.dat
traj_hist_file = traj_hist_wl3.dat
topology = hairpin.top
conf_file = last_conf.dat
trajectory_file = traj_us_wl3.dat
energy_file = energy_us_wl3.dat
last_conf_file = last_conf.dat
print_conf_interval = 100000
print_energy_every = 500000
no_stdout_energy = 1
restart_step_counter = 1
refresh_vel = 1
time_scale = linear
